CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS productdb;
CREATE DATABASE IF NOT EXISTS orderdb;

GRANT ALL PRIVILEGES ON userdb.* TO 'diego'@'%';
GRANT ALL PRIVILEGES ON productdb.* TO 'diego'@'%';
GRANT ALL PRIVILEGES ON orderdb.* TO 'diego'@'%';

FLUSH PRIVILEGES;
