CREATE DATABASE IF NOT EXISTS users_db;
CREATE DATABASE IF NOT EXISTS products_db;
CREATE DATABASE IF NOT EXISTS orders_db;

GRANT ALL PRIVILEGES ON users_db.* TO 'diego'@'%';
GRANT ALL PRIVILEGES ON products_db.* TO 'diego'@'%';
GRANT ALL PRIVILEGES ON orders_db.* TO 'diego'@'%';

FLUSH PRIVILEGES;
