server:
  port: 0

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: orders-service
          uri: http://orders-service
          predicates:
            - Path=/orders/**

        - id: products-service
          uri: http://products-service
          predicates:
            - Path=/products/**

        - id: users-service
          uri: http://users-service
          predicates:
            - Path=/users/**

        - id: auth-service
          uri: http://users-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    enabled: false

jwt:
  secret: q3W9y6kLZ4sVZk8W9Z2YxR1Z9K6Q0c1L
