server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/orders_db
    username: diego
    password: Diegomysql03092005!
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orders-service
  jpa:
    show-sql: true
    hibernate:  
      ddl-auto: update
  cloud:
    discovery:
      enabled: false
    loadbalancer:
      enabled: false


eureka:
  client:
    enabled: false
  
jwt:
  secret: q3W9y6kLZ4sVZk8W9Z2YxR1Z9K6Q0c1L