server:
  port: 8080

spring:
  application:
    name: products-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://mysql:3306/products_db
    username: diego
    password: Diegomysql03092005!
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    enabled: false

jwt:
  secret: q3W9y6kLZ4sVZk8W9Z2YxR1Z9K6Q0c1L