server:
  port: 8082

spring:
  application:
    name: users-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/users_db
    username: diego
    password: Diegomysql03092005!

jwt:
  secret: q3W9y6kLZ4sVZk8W9Z2YxR1Z9K6Q0c1L
